name: Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '15'
      - name: Install npm 7
        run: npm install -g npm@7
      - name: Install everything else
        working-directory: ./codebase/rdicidr-0.1.0
        run: |
          npm install
          npm run lint
          npm run prettier
          npm run test
          npm run build
        
